//
// Created by jaume on 1/28/21.
//

#ifndef COMMOTALKIE_INCLUDE_APPLICATION_CONFIG_H_
#define COMMOTALKIE_INCLUDE_APPLICATION_CONFIG_H_

#define PORT_INDEX    1
#define ID_INDEX      2

#endif //COMMOTALKIE_INCLUDE_APPLICATION_CONFIG_H_
