//
// Created by jaume on 6/11/21.
//

#ifndef COMMOTALKIE_INCLUDE_MESSAGE_MESSAGECONFIG_H_
#define COMMOTALKIE_INCLUDE_MESSAGE_MESSAGECONFIG_H_

#define PORT_INDEX    1
#define ID_INDEX      2

#define MESSAGE_LENGTH          12
#define MESSAGE_META_LENGTH     3

#endif //COMMOTALKIE_INCLUDE_MESSAGE_MESSAGECONFIG_H_
